<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\HttpFoundation\File\Exception\UploadException" namespace="Symfony\Component\HttpFoundation\File\Exception" name="UploadException" abstract="false" final="false" start="19" end="21">
  <file path="/home/web/example/src/freegame_developer/vendor/symfony/http-foundation/File/Exception" file="UploadException.php" realpath="/home/web/example/src/freegame_developer/vendor/symfony/http-foundation/File/Exception/UploadException.php" size="461" time="2016-10-24T14:36:35+00:00" unixtime="1477319795" sha1="d3a6378f918ef34a8591e649fd359f66de98b4bc" relative="freegame_developer/vendor/symfony/http-foundation/File/Exception/UploadException.php"/>
  <docblock>
    <description compact="Thrown when an error occurred during file upload."/>
    <author value="Bernhard Schussek &lt;bschussek@gmail.com&gt;"/>
  </docblock>
  <extends full="Symfony\Component\HttpFoundation\File\Exception\FileException" namespace="Symfony\Component\HttpFoundation\File\Exception" name="FileException"/>
</class>
