<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Process\Exception\RuntimeException" namespace="Symfony\Component\Process\Exception" name="RuntimeException" abstract="false" final="false" start="19" end="21">
  <file path="/home/web/example/src/freegame_developer/vendor/symfony/process/Exception" file="RuntimeException.php" realpath="/home/web/example/src/freegame_developer/vendor/symfony/process/Exception/RuntimeException.php" size="481" time="2016-09-29T02:20:21+00:00" unixtime="1475115621" sha1="c166d875f9b7b1503969bb0e28b79842218ff8e9" relative="freegame_developer/vendor/symfony/process/Exception/RuntimeException.php"/>
  <docblock>
    <description compact="RuntimeException for the Process Component."/>
    <author value="Johannes M. Schmitt &lt;schmittjoh@gmail.com&gt;"/>
  </docblock>
  <extends full="RuntimeException" namespace="" name="RuntimeException"/>
  <implements full="Symfony\Component\Process\Exception\ExceptionInterface" namespace="Symfony\Component\Process\Exception" name="ExceptionInterface"/>
</class>
