<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Debug\Exception\UndefinedFunctionException" namespace="Symfony\Component\Debug\Exception" name="UndefinedFunctionException" abstract="false" final="false" start="19" end="33">
  <file path="/home/web/example/src/freegame_developer/vendor/symfony/debug/Exception" file="UndefinedFunctionException.php" realpath="/home/web/example/src/freegame_developer/vendor/symfony/debug/Exception/UndefinedFunctionException.php" size="811" time="2016-09-06T07:26:07+00:00" unixtime="1473146767" sha1="98b14a71f6d27b5c07fe6552306145d4e9085ae4" relative="freegame_developer/vendor/symfony/debug/Exception/UndefinedFunctionException.php"/>
  <docblock>
    <description compact="Undefined Function Exception."/>
    <author value="Konstanton Myakshin &lt;koc-dp@yandex.ru&gt;"/>
  </docblock>
  <extends full="Symfony\Component\Debug\Exception\FatalErrorException" namespace="Symfony\Component\Debug\Exception" name="FatalErrorException"/>
  <constructor name="__construct" start="21" end="32" abstract="false" final="false" static="false" visibility="public">
    <parameter name="message" byreference="false" type="{unknown}"/>
    <parameter name="previous" byreference="false" type="object">
      <type full="ErrorException" namespace="" name="ErrorException"/>
    </parameter>
  </constructor>
</class>
