<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Debug\Exception\FatalThrowableError" namespace="Symfony\Component\Debug\Exception" name="FatalThrowableError" abstract="false" final="false" start="19" end="44">
  <file path="/home/web/example/src/freegame_developer/vendor/symfony/debug/Exception" file="FatalThrowableError.php" realpath="/home/web/example/src/freegame_developer/vendor/symfony/debug/Exception/FatalThrowableError.php" size="1076" time="2016-09-06T07:26:07+00:00" unixtime="1473146767" sha1="fadecc4b52f837ca26bea5c25183e1909451283d" relative="freegame_developer/vendor/symfony/debug/Exception/FatalThrowableError.php"/>
  <docblock>
    <description compact="Fatal Throwable Error."/>
    <author value="Nicolas Grekas &lt;p@tchwork.com&gt;"/>
  </docblock>
  <extends full="Symfony\Component\Debug\Exception\FatalErrorException" namespace="Symfony\Component\Debug\Exception" name="FatalErrorException"/>
  <constructor name="__construct" start="21" end="43" abstract="false" final="false" static="false" visibility="public">
    <parameter name="e" byreference="false" type="object">
      <type full="Throwable" namespace="" name="Throwable"/>
    </parameter>
  </constructor>
</class>
