
** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): CRITICAL **: volume_control_set_volume_internal: assertion '_tmp1_ == PA_CONTEXT_READY' failed

** (process:3041): CRITICAL **: file /build/buildd/indicator-sound-12.10.2+14.04.20140401/obj-x86_64-linux-gnu/src/volume-control.c: line 1775: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No such interface (g-dbus-error-quark, 16)

** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3041): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): CRITICAL **: volume_control_set_volume_internal: assertion '_tmp1_ == PA_CONTEXT_READY' failed

** (process:3011): CRITICAL **: file /build/buildd/indicator-sound-12.10.2+14.04.20140401/obj-x86_64-linux-gnu/src/volume-control.c: line 1775: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No such interface (g-dbus-error-quark, 16)

** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:3011): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

